/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author roger
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TESTE
     */
    public ViewPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        ImageIcon icon = new ImageIcon(getClass().getResource(
            "/imagens/fundo2.jpg"));
    Image image = icon.getImage();
    jDesktopPane1 = new javax.swing.JDesktopPane(){

        public void paintComponent(Graphics g){
            g.drawImage(image,0,0,getWidth(), getHeight(), this);

        };
    };
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenuOperacao = new javax.swing.JMenu();
    jMenuItemSair = new javax.swing.JMenuItem();
    jMenuCadastros = new javax.swing.JMenu();
    jMenu1 = new javax.swing.JMenu();
    jMenuItemGrupoDeUsuarios = new javax.swing.JMenuItem();
    jMenuItemUsuarios = new javax.swing.JMenuItem();
    jMenu6 = new javax.swing.JMenu();
    jMenuItemContinente = new javax.swing.JMenuItem();
    jMenuItemPais = new javax.swing.JMenuItem();
    jMenuItemEstado = new javax.swing.JMenuItem();
    jMenuItemMunicipio = new javax.swing.JMenuItem();
    jMenuItemCidade = new javax.swing.JMenuItem();
    jMenuItemBairroZona = new javax.swing.JMenuItem();
    jMenu7 = new javax.swing.JMenu();
    jMenu8 = new javax.swing.JMenu();
    jMenuRelatorios = new javax.swing.JMenu();
    jMenuFerramentas = new javax.swing.JMenu();

    jMenuItem6.setText("jMenuItem6");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("          Projeto Arib - Página Principal 1ª versão");

    javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
    jDesktopPane1.setLayout(jDesktopPane1Layout);
    jDesktopPane1Layout.setHorizontalGroup(
        jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 916, Short.MAX_VALUE)
    );
    jDesktopPane1Layout.setVerticalGroup(
        jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 543, Short.MAX_VALUE)
    );

    jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));

    jMenuOperacao.setText("Operação");

    jMenuItemSair.setText("Sair");
    jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemSairActionPerformed(evt);
        }
    });
    jMenuOperacao.add(jMenuItemSair);

    jMenuBar1.add(jMenuOperacao);

    jMenuCadastros.setText("Cadastros");

    jMenu1.setText("Segurança");

    jMenuItemGrupoDeUsuarios.setText("Grupos de Usuários");
    jMenuItemGrupoDeUsuarios.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemGrupoDeUsuariosActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemGrupoDeUsuarios);

    jMenuItemUsuarios.setText("Usuários");
    jMenuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemUsuariosActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemUsuarios);

    jMenuCadastros.add(jMenu1);

    jMenu6.setText("Localização");

    jMenuItemContinente.setText("Continente");
    jMenuItemContinente.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemContinenteActionPerformed(evt);
        }
    });
    jMenu6.add(jMenuItemContinente);

    jMenuItemPais.setText("País");
    jMenuItemPais.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemPaisActionPerformed(evt);
        }
    });
    jMenu6.add(jMenuItemPais);

    jMenuItemEstado.setText("Estado");
    jMenuItemEstado.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemEstadoActionPerformed(evt);
        }
    });
    jMenu6.add(jMenuItemEstado);

    jMenuItemMunicipio.setText("Município");
    jMenuItemMunicipio.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemMunicipioActionPerformed(evt);
        }
    });
    jMenu6.add(jMenuItemMunicipio);

    jMenuItemCidade.setText("Cidade");
    jMenuItemCidade.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemCidadeActionPerformed(evt);
        }
    });
    jMenu6.add(jMenuItemCidade);

    jMenuItemBairroZona.setText("Bairro / Zona");
    jMenuItemBairroZona.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemBairroZonaActionPerformed(evt);
        }
    });
    jMenu6.add(jMenuItemBairroZona);

    jMenuCadastros.add(jMenu6);

    jMenu7.setText("Pessoas / Empresas");
    jMenuCadastros.add(jMenu7);

    jMenu8.setText("Produtos");
    jMenuCadastros.add(jMenu8);

    jMenuBar1.add(jMenuCadastros);

    jMenuRelatorios.setText("Relatórios");
    jMenuBar1.add(jMenuRelatorios);

    jMenuFerramentas.setText("Ferramentas");
    jMenuBar1.add(jMenuFerramentas);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jDesktopPane1)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemGrupoDeUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGrupoDeUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemGrupoDeUsuariosActionPerformed

    private void jMenuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemUsuariosActionPerformed

    private void jMenuItemContinenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContinenteActionPerformed
        try {
           new ViewCadContinente(this, true).setVisible(true);
            this.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItemContinenteActionPerformed

    private void jMenuItemPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemPaisActionPerformed

    private void jMenuItemEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemEstadoActionPerformed

    private void jMenuItemMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMunicipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemMunicipioActionPerformed

    private void jMenuItemCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCidadeActionPerformed

    private void jMenuItemBairroZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBairroZonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemBairroZonaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItemBairroZona;
    private javax.swing.JMenuItem jMenuItemCidade;
    private javax.swing.JMenuItem jMenuItemContinente;
    private javax.swing.JMenuItem jMenuItemEstado;
    private javax.swing.JMenuItem jMenuItemGrupoDeUsuarios;
    private javax.swing.JMenuItem jMenuItemMunicipio;
    private javax.swing.JMenuItem jMenuItemPais;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemUsuarios;
    private javax.swing.JMenu jMenuOperacao;
    private javax.swing.JMenu jMenuRelatorios;
    // End of variables declaration//GEN-END:variables
}
